#pragma once

#include "stm32h7xx.h"

#define BOARD_LED_GPIO_PORT GPIOH
#define BOARD_LED_GPIO_PIN GPIO_PIN_10
#define BOARD_LED_ACTIVE_LEVEL GPIO_PIN_SET
#define BOARD_LED_INACTIVE_LEVEL GPIO_PIN_RESET
